// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMpOuWs6ZIW1A7xHSrE5Fb3h41WfYsrk',
    appId: '1:289699688566:web:2739e69793387b4e7a2f57',
    messagingSenderId: '289699688566',
    projectId: 'flutter-bf075',
    authDomain: 'flutter-bf075.firebaseapp.com',
    storageBucket: 'flutter-bf075.firebasestorage.app',
    measurementId: 'G-CL39WQ0R3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRohGKmjEZAKtyubYihqI66w-gXvD7w4c',
    appId: '1:289699688566:android:ee9a9d4d6a73389c7a2f57',
    messagingSenderId: '289699688566',
    projectId: 'flutter-bf075',
    storageBucket: 'flutter-bf075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH1OiumRYF5MeqjZV4wRgBIe_FZJo0bAI',
    appId: '1:289699688566:ios:9487b234371f1d477a2f57',
    messagingSenderId: '289699688566',
    projectId: 'flutter-bf075',
    storageBucket: 'flutter-bf075.firebasestorage.app',
    iosBundleId: 'com.example.todoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdMpOuWs6ZIW1A7xHSrE5Fb3h41WfYsrk',
    appId: '1:289699688566:web:e4ff2a962f8126247a2f57',
    messagingSenderId: '289699688566',
    projectId: 'flutter-bf075',
    authDomain: 'flutter-bf075.firebaseapp.com',
    storageBucket: 'flutter-bf075.firebasestorage.app',
    measurementId: 'G-ZNP0K15XTB',
  );
}
